### PR TITLE
Client qol

### PR DESCRIPTION
**Pull request by stephen-lt-sl**
@stevenhillcox @sievins @jebbinSCL

This branch cleans up some of the client code and adds several purely client-facing features for formatting and displaying conversations: showing names and timestamps for individual messages, showing names for conversations, automatic server-polling for new messages, and making conversations scrollable.

### CODE REVIEW

**Comment by jebbinSCL** [comment]
What do you mean by qol in the title? Quality of life?

**Comment by stephen-lt-sl** [comment]
Yeah - it seemed an appropriate name at the time I opened the branch, although I wasn't sure about the appropriate way to case a branch name; having it all lower case doesn't make it very clear, especially since github automatically sets the first character to upper case.

**Comment by jebbinSCL** [comment]
I think the trouble is that you have a lot of small adjustments in here, so its tough to give it a simple name. Leave it for now, but this was a pull request that should have been broken down more again. 

Its good to do refactoring with the feature changes, but each pull request needs to have a clear simple objective. A pull request title should be something like "Show user names in conversations" or "Show message names and timestamps for individual messages" or "Show message metadata for individual messages", not all combined.

**Comment by stephen-lt-sl** [comment]
Alright, I'll make sure to keep my feature branches as specific as reasonably possible from here onwards. Should I proceed with the merge?

**Comment by jebbinSCL** [comment]
Not yet, I'll go through it in a few minutes.

**Comment by jebbinSCL** [comment]
Also, doesn't need to be absolutely atomic / tiny, just a clear objective for each pull request is good.

**Comment by jebbinSCL** [comment]
Ok, so everything is generally fine, but I think you need to start some further refactoring to get things more in line with how things should be with angular. First split out your controller and directive (And anything else you are creating that is a main 'type' of angular.) You'll also want to split your fetching code from your controller into a service. Take a look at the angular 1 docs on services. That will be a good start for now. 

Merge this for now, and make these changes in your next pull request?

**Comment by jebbinSCL** [comment]
:ship:

**Comment by stephen-lt-sl** [comment]
That's my plan for the next couple of branches - refactoring the server logic to use the API for MongoDriver in an up-to-date way (including using promises) and properly restructuring the client angular logic.

**Comment by jebbinSCL** [comment]
Great, looking forward to it :+1:

**Pull request merged**
